project:
  type: website
  output-dir: docs

website:
  title: "Large Data in R"
  repo-url: https://github.com/astamm/large-data-in-r/
  repo-actions: [edit, source, issue]
  page-footer:
    background: light
    left: Copyright 2024, Aymeric Stamm
    right: This website is built with [Quarto](https://quarto.org/)
  navbar:
    left:
      - text: "Parquet"
        href: parquet.qmd
    right:
      - icon: github
        href: https://github.com/astamm/large-data-in-r/

  search:
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
